### PR TITLE
Custom theme and further user-config support

### PR DESCRIPTION
**Pull request by eric-hansen**
I'll create a PR soon (if possible) for the wiki to document the user config stuff.  I feel this is the last link to making it really viable based on how I've been incorporating it into my flow.  But as it has evolved extensively all things considered, I think documentation will be helpful.

If I can't do anything w/ the Wiki then I'll create a PR of Markdown files in `./docs` or whichever folder you prefer, so there's at least something.

### CODE REVIEW

**Comment by eric-hansen** [comment]
As an aside here's a branch w/ the Markdown doc: https://github.com/eric-hansen/VapourNvim/blob/user-config-docs/docs/user-config.md

I can PR this if you like.

**Comment by hackorum** [comment]
That's a great readme. I'll copy the markdown and make a wiki page.

**Comment by hackorum** [comment]
I've made the wiki page [here](https://github.com/hackorum/VapourNvim/wiki/User-Configuration)

**Comment by eric-hansen** [comment]
I'm glad it was helpful. :)  Hope things are well for ya by the way sir.

**Comment by hackorum** [comment]
Yes, all is well, thanks for asking. Sir is a big word, I just entered 8th grade of school :-)

**Comment by eric-hansen** [comment]
Ah, well great job on this. :) I like the minimalistic feel of it.

**Pull request merged**
