### PR TITLE
Allow custom which-key mappings

### PR DESCRIPTION
**Pull request by eric-hansen**

### CODE REVIEW

**Comment by eric-hansen** [comment]
I ended up changing some of this in a different branch to be more forgiving.  If you want I can merge that branch into this as well.

Namely this commit https://github.com/eric-hansen/VapourNvim/commit/52d2f5ceac384818fc838aa6493f1d71c6875456 but there's more to it than just that I have yet to push that also allows defining a custom theme.

**Comment by hackorum** [comment]
I think you should merge the branches together.

**Comment by eric-hansen** [comment]
> I think you should merge the branches together.

Cool.  I'll do that in a couple hours or so and then we can get this merged in. :)

**Comment by eric-hansen** [comment]
Okay, I updated the PR to have the custom theme support and such, so it's good for your review.

I added the `Vapour.utils.plugins.add_user` because I realized if someone (like me, for example) wanted to add a plugin in a sub-lua file (i.e.: `lua/vapour/user-config/theme/init.lua`) there really wasn't a clean way to add plugins in there if we already defined it in the `user-config/init.lua` file for example.  So now in any Lua file you can do `Vapour.utils.plugins.add_user {'some/repo', {...}}` for example and it will add it to Packer for installation.

**Comment by hackorum** [comment]
Cool! It would be great if you could also write a readme which explains everything about the user configuration. You don't need to do it but I guess it would be helpful for new users.

**Comment by eric-hansen** [comment]
> Cool! It would be great if you could also write a readme which explains everything about the user configuration. You don't need to do it but I guess it would be helpful for new users.

It can either be a readme or in the wiki, I don't know what would be easier to manage.  But I think it would be helpful for anyone else who chooses to use Vapour. :)

**Comment by hackorum** [comment]
IMO a wiki would be better.

**Pull request merged**
